# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: VU IT Mac Help
emailaddress: servicedesk.it@vu.nl
description: > # this means to ignore newlines until "baseurl:"
  This site aims to provide information and news to Mac Users at the
  Vrije Universiteit Amsterdam.
baseurl: /macOS-web-help # the subpath of your site, e.g. /blog
# twitter_username: jekyllrb
# github_username:  jekyll

# Add _pages and _files
include: ["_pages"]

# Build settings
markdown: kramdown
theme: minima
exclude: [vendor]
paginate: 5

collections:
  email:
    output: true
    permalink: /:collection/:path/
    title: Set up Email
  file_access:
    output: true
    permalink: /:collection/:path/
    title: Set up File Access
  communication:
    output: true
    permalink: /:collection/:path/
    title: Set up Skype for Business
